### ISSUE TITLE
omni.path_tracing not valid

### ISSUE THREAD

**Issue by ashleygoldstein** [iirthw/kit-extension-path-tracking#2]
Hey there, I am on the NVIDIA Omniverse team. Just wanted to let you know we cannot pull your extension because omni.path_tracing is not a valid extension name. Something like ext.path.tracing would be better.

**Comment by omnioverflow** [comment]
@ashleygoldstein Hi, many thanks! I really appreciate your feedback.
Indeed, I should have used correct form of reverse domain name notation for the extension name. I assume that extensions starting with omni are reserved for those developed by NVIDIA inhouse and shipped out-of-the-box with NVIDIA Omniverse.

Just merged PR #3 where the extension is renamed to `ext.path.tracking`.
Are you able to pull the extension now?
Thanks.

**Comment by ashleygoldstein** [comment]
Thanks for updating! If there are any more issues I will be sure to let you know, I notified the contest team that your extension has been updated and ready to be pulled

**Comment by omnioverflow** [comment]
Great, thanks! I will be glad to help if there any further issues.

It might be a bit tricky to get started using it for a first time when not using a preset scene (i.e. get vehicle to curve attachment in a right way). And there are a few inherent limitations in certain cases due to implementation details of the vehicle control approach (the extension is still in beta).

I've been also notified by one of your colleagues at NVIDIA who came across the extension on github, that it is apparently not listed among NVIDIA OV contest submissions. I am wondering if I made some mistake during the time when I sent the extension via the official submission form

**Comment by ashleygoldstein** [comment]
Feel free to submit it again! You should have gotten a confirmation email when you submitted so if you didn't that could be why
